### ISSUE TITLE
请问您的毕业论文和三个数据集的全量数据，能否分享一下呢？感谢！

### ISSUE THREAD

**Issue by hualitlc** [origin-coding/aesthetic#1]
这套美学评价的代码工程写的非常棒，期待深入学习一下，所以想看看您当时整体的研究思路，希望能够读一下您的论文，打扰了，感谢！

**Comment by origin-coding** [comment]
> 这套美学评价的代码工程写的非常棒，期待深入学习一下，所以想看看您当时整体的研究思路，希望能够读一下您的论文，打扰了，感谢！

抱歉，这个已经无法提供了。我在今年年初的时候重装了几次操作系统，由于没做好备份，这些东西被格式化了。
